spec:
  template:
    spec:
      containers:
        - env:
            - name: MESSAGING_SERVICE_HOST
              valueFrom:
                configMapKeyRef:
                  name: messaging-service
                  key: MESSAGING_SERVICE_HOST
            - name: MESSAGING_SERVICE_PORT
              valueFrom:
                configMapKeyRef:
                  name: messaging-service
                  key: MESSAGING_SERVICE_PORT
